// ignore_for_file: constant_identifier_names

import 'package:flutter/material.dart';

const DARK_PRIMARY_COLOR = Color(0xFF303F9F);
//const LIGHT_PRIMARY_COLOR = const Color(0xFFC5CAE9);
//const PRIMARY_COLOR = const Color(0xFF3F51B5);
const PRIMARY_COLOR = Color(0xFF02499B);
const SPLASH_BACKGROUND = Color(0xFF081238);
const LIGHT_PRIMARY_COLOR = Color(0xFFE5F7FE);
const TEXT_ICONS_COLOR = Color(0xFFFFFFFF);
const LIGHT_ACCENT_COLOR = Color(0xFFFFF3CC);
const ACCENT_COLOR = Color(0xFFF6A51C);
const PRIMARY_TEXT_COLOR = Color(0xFF2F2E41);
const SECONDARY_TEXT_COLOR = Color(0x6602499B);
const DIVIDER_COLOR = Color(0xFFBDBDBD);
const LIGHT_DIVIDER_COLOR = Color(0xFFCFD8DC);
const DISABLED_COLOR = Color(0xFF212121);
const SUCCESS_COLOR = Color(0xFF04C104);
const DANGER_COLOR = Color(0xFFED170D);
const WARNING_COLOR = Color(0xFFF6A51C);
const BUTTON_COLOR = Color(0xFFFF9356);
const LIGHT_DISABLED_COLOR = Color(0xFFBDBDBD);

const BASED_COLOR_NAVY = Color(0xFF081238);
const BASED_COLOR_NAVY_GREY = Color(0xFF2B3458);
const BASED_COLOR_WHITE = Colors.white;
const BASED_COLOR_GREY = Color(0xFFF6F6F6);

const VISUAL_COLOR_NAVY = Color(0xFF081238);
const VISUAL_COLOR_ORANGE = Color(0xFFFF9356);
const VISUAL_COLOR_MAGENTA = Color(0xFFDA3164);
const VISUAL_COLOR_PURPLE = Color(0xFF593376);
const VISUAL_COLOR_MAROON = Color(0xFF9B1940);
const VISUAL_COLOR_GREEN = Color(0xFF2B6E46);
const VISUAL_COLOR_DARK_BLUE = Color(0xFF394161);
const VISUAL_COLOR_BLUE = Color(0xFF1A254E);
const VISUAL_COLOR_FANTA = Color(0xFFE55782);
const VISUAL_COLOR_NEW_PURPLE = Color(0xFF74508F);

const VISUAL_LIGHT_YELLOW = Color(0xFFFDEBBC);
const VISUAL_LIGHT_PURPLE = Color(0xFFEDDEF4);
const VISUAL_LIGHT_GREEN = Color(0xFFD9F2D9);
const VISUAL_LIGHT_RED = Color(0xFFF4DEE8);
const VISUAL_LIGHT_GREY = Color(0xFFE4E0E0);

const TEXT_COLOR_ORANGE = Color(0xFFFF9356);
const TEXT_COLOR_BLACK = Colors.black;
const TEXT_COLOR_WHITE = Colors.white;
const TEXT_DARK_GREY = Color(0xFF37383A);
const TEXT_COLOR_GREY = Color(0xFF545353);
const TEXT_BROWN_GREY = Color(0xFF797777);
const TEXT_LIGHT_GREY = Color(0xFFCCCCCC);

const COLOR_AKADEMI = [
  BASED_COLOR_NAVY,
  VISUAL_COLOR_MAROON,
  Color(0xFF2B6F46),
];
const COLOR_AKADEMI_BG = [
  Color(0xFF262E4E),
  Color(0xFFAD3458),
  Color(0xFF468861)
];

const COLOR_HOSTORY = [
  VISUAL_COLOR_NAVY,
  VISUAL_COLOR_MAGENTA,
  VISUAL_COLOR_PURPLE,
];

const COLOR_HOSTORY_BG = [
  VISUAL_COLOR_DARK_BLUE,
  VISUAL_COLOR_FANTA,
  VISUAL_COLOR_NEW_PURPLE,
];
